# -*- coding: utf-8 -*-
"""PSO program 1_Suci Fransisca Sisilia

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-4wLPQzpBPBXi-XdSIN8PvYPBZdT0kzl

**Program 1**

Penerapan program menggunakan python
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Membaca data posisi dan kecepatan dari file Excel
file_path = "PSO_Completed_With_All_Dynamic_Formulas.xlsx"  # Gantilah dengan path ke file Anda
df = pd.read_excel(file_path)

# Menyusun data posisi dan kecepatan dari kolom Excel
positions = df[['Posisi X', 'Posisi Y']].values  # Mengambil posisi X dan Y
velocities = np.random.uniform(-0.5, 0.5, positions.shape)  # Kecepatan acak
p_best_positions = positions.copy()  # Posisi terbaik individu
p_best_values = np.linalg.norm(positions - np.array([10, 10]), axis=1)  # Jarak ke target (10, 10)
g_best_position = positions[np.argmin(p_best_values)]  # Posisi terbaik global
g_best_value = np.min(p_best_values)  # Nilai terbaik global

# Fungsi untuk menghitung jarak ke target
def calculate_distance(position):
    return np.linalg.norm(position - np.array([10, 10]))

# Fungsi untuk memperbarui kecepatan dan posisi partikel
def update_velocity_and_position(positions, velocities, p_best_positions, g_best_position):
    r1 = np.random.random(positions.shape)
    r2 = np.random.random(positions.shape)

    # Update kecepatan
    velocities = (0.8 * velocities
                  + 1.5 * r1 * (p_best_positions - positions)
                  + 1.5 * r2 * (g_best_position - positions))

    # Update posisi
    positions = positions + velocities
    return positions, velocities

# Iterasi PSO
num_iterations = 10
for iteration in range(num_iterations):
    for i in range(len(positions)):
        # Hitung jarak ke target untuk setiap partikel
        distance = calculate_distance(positions[i])

        # Update P_best jika ditemukan posisi yang lebih baik
        if distance < p_best_values[i]:
            p_best_positions[i] = positions[i]
            p_best_values[i] = distance

    # Update G_best
    best_particle_index = np.argmin(p_best_values)
    g_best_position = p_best_positions[best_particle_index]
    g_best_value = p_best_values[best_particle_index]

    # Update posisi dan kecepatan
    positions, velocities = update_velocity_and_position(positions, velocities, p_best_positions, g_best_position)

    # Menampilkan hasil pada setiap iterasi
    print(f"Iterasi {iteration+1}:")
    print(f"Posisi Terbaik Global: {g_best_position}, Jarak ke Target: {g_best_value}\n")

    # Visualisasi pergerakan partikel
    plt.scatter(positions[:, 0], positions[:, 1], color='blue', label='Partikel')
    plt.scatter(10, 10, color='red', label='Target')
    plt.scatter(g_best_position[0], g_best_position[1], color='green', label='Posisi Terbaik Global')
    plt.xlim(0, 12)
    plt.ylim(0, 12)
    plt.legend()
    plt.title(f"Iterasi {iteration+1}")
    plt.grid(True)
    plt.show()

# Menampilkan posisi terbaik global yang ditemukan setelah iterasi
print(f"Posisi terbaik global yang ditemukan: {g_best_position}")

